### ISSUE TITLE
Error loading `AutoModelForCausalLM` in `examples/generate_act_scales.py`

### ISSUE THREAD

**Issue by julian-q** [mit-han-lab/smoothquant#46]
Thank you for providing this great repo!

I'm trying to generate activation scales for OPT-350M:
```bash
$ python examples/generate_act_scales.py --model-name ~/huggingface-models/opt-350m/ --output-path act_scales/opt-350m.pt
```
And I get the following error from `transformers`:
```
Traceback (most recent call last):
  File "examples/generate_act_scales.py", line 51, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "examples/generate_act_scales.py", line 35, in main
    model, tokenizer = build_model_and_tokenizer(args.model_name)
  File "examples/generate_act_scales.py", line 15, in build_model_and_tokenizer
    model = AutoModelForCausalLM.from_pretrained(model_name, **kwargs)
  File "/usr/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 446, in from_pretrained
    return model_class.from_pretrained(pretrained_model_name_or_path, *model_args, config=config, **kwargs)
  File "/usr/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2225, in from_pretrained
    model, missing_keys, unexpected_keys, mismatched_keys, error_msgs = cls._load_pretrained_model(
  File "/usr/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2279, in _load_pretrained_model
    if device_map is not None and "disk" in device_map.values() and offload_folder is None:
AttributeError: 'str' object has no attribute 'values'
```

Output of `pip show transformers`:
```
Name: transformers
Version: 4.20.0
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache
Location: /usr/lib/python3.8/site-packages
Requires: pyyaml, filelock, packaging, requests, huggingface-hub, tokenizers, tqdm, numpy, regex
Required-by:
```

**Comment by julian-q** [comment]
Fixed by upgrading `transformers` to something `>=4.24`.

`pip install --upgrade transformers`
